//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Plugin.Shipping.PPL.Ktm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://KTM/ASM/Ktm.asmx", ConfigurationName="Ktm.KtmSoap")]
    public interface KtmSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KTM/ASM/Ktm.asmx/GetKTMDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.PPL.Ktm.KTMDetail GetKTMDetail(string customerID, string customerDepID, string KTMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KTM/ASM/Ktm.asmx/GetKTMDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.PPL.Ktm.KTMDetail> GetKTMDetailAsync(string customerID, string customerDepID, string KTMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KTM/ASM/Ktm.asmx/GetKTMList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[] GetKTMList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KTM/ASM/Ktm.asmx/GetKTMList", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[]> GetKTMListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KTM/ASM/Ktm.asmx/GetAllKTMList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[] GetAllKTMList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KTM/ASM/Ktm.asmx/GetAllKTMList", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[]> GetAllKTMListAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://KTM/ASM/Ktm.asmx")]
    public partial class KTMDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gpsNField;
        
        private string gpsEField;
        
        private string positionField;
        
        private string openTimeField;
        
        private string qrCodeField;
        
        private string customerName1Field;
        
        private string customerName2Field;
        
        private string kTMIDField;
        
        private string countryIdField;
        
        private string cityField;
        
        private string street1Field;
        
        private string zipCodeField;
        
        private string customerIdField;
        
        private string customerDepIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string gpsN {
            get {
                return this.gpsNField;
            }
            set {
                this.gpsNField = value;
                this.RaisePropertyChanged("gpsN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string gpsE {
            get {
                return this.gpsEField;
            }
            set {
                this.gpsEField = value;
                this.RaisePropertyChanged("gpsE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string openTime {
            get {
                return this.openTimeField;
            }
            set {
                this.openTimeField = value;
                this.RaisePropertyChanged("openTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string qrCode {
            get {
                return this.qrCodeField;
            }
            set {
                this.qrCodeField = value;
                this.RaisePropertyChanged("qrCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string customerName1 {
            get {
                return this.customerName1Field;
            }
            set {
                this.customerName1Field = value;
                this.RaisePropertyChanged("customerName1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string customerName2 {
            get {
                return this.customerName2Field;
            }
            set {
                this.customerName2Field = value;
                this.RaisePropertyChanged("customerName2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string KTMID {
            get {
                return this.kTMIDField;
            }
            set {
                this.kTMIDField = value;
                this.RaisePropertyChanged("KTMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string countryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
                this.RaisePropertyChanged("countryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
                this.RaisePropertyChanged("street1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string customerDepId {
            get {
                return this.customerDepIdField;
            }
            set {
                this.customerDepIdField = value;
                this.RaisePropertyChanged("customerDepId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KtmSoapChannel : Nop.Plugin.Shipping.PPL.Ktm.KtmSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KtmSoapClient : System.ServiceModel.ClientBase<Nop.Plugin.Shipping.PPL.Ktm.KtmSoap>, Nop.Plugin.Shipping.PPL.Ktm.KtmSoap {
        
        public KtmSoapClient() {
        }
        
        public KtmSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KtmSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KtmSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KtmSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Nop.Plugin.Shipping.PPL.Ktm.KTMDetail GetKTMDetail(string customerID, string customerDepID, string KTMID) {
            return base.Channel.GetKTMDetail(customerID, customerDepID, KTMID);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.PPL.Ktm.KTMDetail> GetKTMDetailAsync(string customerID, string customerDepID, string KTMID) {
            return base.Channel.GetKTMDetailAsync(customerID, customerDepID, KTMID);
        }
        
        public Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[] GetKTMList() {
            return base.Channel.GetKTMList();
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[]> GetKTMListAsync() {
            return base.Channel.GetKTMListAsync();
        }
        
        public Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[] GetAllKTMList() {
            return base.Channel.GetAllKTMList();
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.PPL.Ktm.KTMDetail[]> GetAllKTMListAsync() {
            return base.Channel.GetAllKTMListAsync();
        }
    }
}
